name: monalisa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/images/Mona_Lisa.jpg

  uses-material-design: true

  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/merriweather/Merriweather-Regular.ttf
        - asset: fonts/merriweather/Merriweather-Bold.ttf
